version: '3'
services:
  ros-kinetic:
    build: .
    container_name: ros_kinetic_dev
    volumes:
      - .:/ros_workspace
      - /home/dan/Projects/Pydrake-robotiq140:/Pydrake-robotiq140
    ports:
      - "11311:11311"
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
      - "ROS_HOSTNAME=localhost"
